### ISSUE TITLE
[PE-D][Tester F] Error message for invalid deadline delete command could be misleading

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103-F09-1/tp#165] opened 2022-10-29 01:59 UTC
Steps to reproduce:
1. Have an existing student (eg A1438807T) with a single deadline task
2. Try to delete the 5th deadline task of the same student (A1438807T) using delete -d i/A1438807T r/5

Actual:
Error message indicating that the rank has to be a valid integer

Expected:
Perhaps an error message to indicate that the rank given is out of range might be more suitable

![image.png](https://raw.githubusercontent.com/marcusczh/ped/main/files/74c8df23-2fcf-474a-ab43-745d1cc87154.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: marcusczh/ped#5

**Comment by RussellDash332** [comment] 2022-10-30 22:12
Duplicate of #203

**Closed by RussellDash332** 2022-10-30 22:12 UTC
Labels: ped.Tester.F
