### ISSUE TITLE
[PE-D][Tester E] Several commands take several seconds to parse and process

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103-F09-1/tp#175] opened 2022-10-29 02:54 UTC
Several commands such as `find` and especially `list` take a few seconds to complete, even with just the 6 entries in the sample data.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: leeianee/ped#2

**Comment by RussellDash332** [comment] 2022-10-30 22:17
Duplicate of #200

**Closed by RussellDash332** 2022-10-30 22:17 UTC
Labels: ped.Tester.E
